                                                 Московский Авиационный Институт  
                                          (Национальный Исследовательский Университет)
                                          
Кафедра: 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»  

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                 Лабораторная работа №1.  
                                                          Тема:  
                                                         «numpy»
                                                         
                                                         
                                                                                                       Группа: М8О – 103М-20
                                                                                        Студент: Проскурин Андрей Кириллович
                                                                                Преподаватель: Поповкин Александр Викторович
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                           Москва  
                                                            2020

**1) Импортировать NumPy под именем np**

In [1]:
import numpy as np

**2) Напечатать версию и конфигурацию**

In [2]:
np.__version__

'1.19.3'

**3) Создать вектор (одномерный массив) размера 10, заполненный нулями**

In [3]:
arr = np.zeros(10, int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


**4) Создать вектор размера 10, заполненный единицами**

In [4]:
arr = np.ones(10, int)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


**5) Создать вектор размера 10, заполненный числом 2.5**

In [5]:
arr = np.full(10, 2.5)
print(arr)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


**6) Как получить документацию о функции numpy.add из командной строки?**

In [6]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

**7) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1**

In [7]:
arr = np.zeros(10, int)
arr[4] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


**8) Создать вектор со значениями от 10 до 49**

In [8]:
arr = np.arange(10, 50, 1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**9) Развернуть вектор (первый становится последним)**

In [9]:
arr = np.arange(10)
print(arr)
arr = arr[::-1]
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


**10) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8**

In [10]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**11) Найти индексы ненулевых элементов в [1, 2, 0, 0, 4, 0]**

In [11]:
arr = np.array([1, 2, 0, 0, 4, 0])
for i in range(len(arr)):
    if arr[i] != 0:
        print("not null index - " + str(i))

not null index - 0
not null index - 1
not null index - 4


**12) Создать массив 3x3x3 со случайными значениями**

In [12]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.82881611 0.51947597 0.48508925]
  [0.8233236  0.99917195 0.61127549]
  [0.77416791 0.00676715 0.21605671]]

 [[0.5971959  0.61811581 0.9664492 ]
  [0.94768723 0.31109543 0.11017572]
  [0.06800355 0.91493787 0.61783254]]

 [[0.99934037 0.28252334 0.14737993]
  [0.65773722 0.64485945 0.92843518]
  [0.01769748 0.95051617 0.26969914]]]


**13) Создать массив 10x10 со случайными значениями, найти минимум и максимум**

In [13]:
arr = np.random.rand(10, 10)
print(arr)
print("Min = " + str(arr.min()))
print("Max = " + str(arr.max()))

[[9.84268279e-01 4.30984061e-01 7.90629671e-01 2.41421498e-03
  7.00833352e-01 9.51326767e-01 3.71646473e-01 5.02009521e-01
  4.78358959e-01 2.72358838e-02]
 [1.44552095e-01 2.25341935e-01 7.37647771e-01 3.00138129e-01
  8.93120016e-01 7.03162984e-01 7.91423755e-01 3.84458735e-01
  7.53418631e-01 7.09622340e-01]
 [3.05078314e-01 7.11152063e-01 7.45638486e-01 9.29563415e-01
  9.13864559e-01 4.74294370e-01 8.05957572e-01 3.90989042e-01
  6.62091609e-01 5.27503792e-01]
 [3.97666672e-01 4.07011263e-01 7.89985213e-01 2.03082720e-01
  8.53012906e-01 3.82796631e-01 7.52429705e-01 8.00589556e-01
  8.83582596e-01 3.30529897e-01]
 [5.43632742e-01 9.36339381e-01 9.46702127e-01 7.12517626e-02
  9.88828766e-01 1.99351070e-01 3.89541138e-01 1.50846413e-01
  9.39721608e-01 9.61366649e-01]
 [7.22408036e-01 1.09579112e-01 6.56256333e-01 3.37454571e-01
  3.48685051e-01 8.40680223e-01 9.12029620e-01 8.34173891e-01
  2.84870839e-01 6.34361308e-01]
 [6.02378821e-01 4.81882635e-01 7.67817148e-01 4.97199482e

**14) Создать случайный вектор размера 30 и найти среднее значение всех элементов**

In [14]:
arr = np.random.rand(30)
arr = np.around(arr, 3)

arr = np.mean(arr)
arr = np.around(arr, 3)
print("arithmetic mean = " + str(arr))

arithmetic mean = 0.521


**15) Создать матрицу с 0 внутри, и 1 на границах**

In [15]:
arr = np.ones([5, 5])
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**16) Выяснить результат следующих выражений:**

        0 * np.nan
        np.nan == np.nan
        np.inf > np.nan
        np.nan - np.nan

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


**17) Создать 5x5 матрицу с 1,2,3,4 диагональю**

In [17]:
arr = np.diag(np.arange(1, 6))
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


**18) Создать 8x8 матрицу и заполнить её в шахматном порядке**

In [18]:
arr = np.zeros([8, 8])
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**19) Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?**

In [19]:
arr = np.unravel_index(100, (6,7,8))
print(arr)

(1, 5, 4)


**20) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile**

In [20]:
arr = np.array([[1, 0], [0, 1]])
newArr = np.tile(arr, [4, 4])
print(newArr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
