                                                 Московский Авиационный Институт  
                                          (Национальный Исследовательский Университет)
                                          
Кафедра: 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»  

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                 Лабораторная работа №3.  
                                                          Тема:  
                                                         «numpy»
                                                         
                                                         
                                                                                                       Группа: М8О – 103М-20
                                                                                        Студент: Проскурин Андрей Кириллович
                                                                                Преподаватель: Поповкин Александр Викторович
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                           Москва  
                                                            2020

In [2]:
import numpy as np
from numpy.lib import stride_tricks

**1)** Дан вектор ```[1, 2, 3, 4, 5]```, построить новый вектор с тремя нулями между каждым значением

In [2]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**2)** Поменять 2 строки в матрице

In [4]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**3)** Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [5]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 7, 24) ( 7, 49) ( 8, 18) ( 8, 65) ( 9, 39) ( 9, 72) (18, 65) (21, 88)
 (21, 95) (22, 25) (22, 63) (24, 49) (25, 63) (30, 33) (30, 38) (33, 38)
 (38, 66) (38, 82) (39, 72) (41, 53) (41, 90) (44, 83) (44, 93) (47, 61)
 (47, 73) (53, 90) (61, 73) (66, 82) (83, 93) (88, 95)]


**4)** Дан массив C; создать массив A, что np.bincount(A) == C

In [8]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


**5)** Посчитать среднее, используя плавающее окно

In [9]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


**6)** Дан вектор Z, построить матрицу, первая строка которой ```(Z[0],Z[1],Z[2])```, каждая последующая сдвинута на 1 (последняя ```(Z[-3],Z[-2],Z[-1])```)  

Функция lib.stride_tricks.as_strided() возвращает представление массива с указанной формой и смещением байтов между элементами для перехода по ним вдоль разных осей.

Представление массива не является его копией, т.е. они ссылаются на одни и те же данные, поэтому изменения в одном из них приведут к изменениям в другом.

In [3]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


**7)** Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [13]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.97248739, -0.7629727 ,  0.86888936, -0.28354725,  0.73201663,
       -0.90674614, -0.6182932 , -0.54344698, -0.68830227, -0.92044873,
       -0.79040096, -0.81149101, -0.34826052, -0.22260731,  0.97348576,
        0.19161704, -0.55587487, -0.54124619,  0.95960435,  0.55653978,
       -0.42473465, -0.31513284,  0.39949825, -0.18554251, -0.58230557,
       -0.24297783, -0.48102044, -0.56867012,  0.74084804,  0.55009164,
       -0.18917123,  0.29616363, -0.81501021,  0.7092604 , -0.1530487 ,
       -0.16431789,  0.96120686, -0.28760517, -0.61267718,  0.97991008,
       -0.81421216, -0.02302994, -0.28006872,  0.20621624, -0.98283421,
        0.5581676 , -0.89439329, -0.18204131,  0.89010662, -0.11234791,
       -0.38922325,  0.92020252,  0.49447171, -0.6610417 , -0.56267843,
        0.08178935,  0.40335744,  0.76956674, -0.25417961, -0.31300241,
        0.09369851, -0.72160925, -0.43038326,  0.62737172,  0.88781697,
        0.83873117, -0.36461091,  0.25143797, -0.59907918,  0.20

**8)** Посчитать ранг матрицы

In [16]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)
print(rank)

10


**9)** Найти наиболее частое значение в массиве

In [17]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


**10)** Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [18]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 3]
   [1 3 0]
   [4 1 2]]

  [[3 3 3]
   [3 0 0]
   [1 2 1]]

  [[3 3 4]
   [0 0 0]
   [2 1 3]]

  [[3 4 0]
   [0 0 4]
   [1 3 2]]

  [[4 0 4]
   [0 4 3]
   [3 2 4]]

  [[0 4 1]
   [4 3 0]
   [2 4 4]]

  [[4 1 4]
   [3 0 0]
   [4 4 4]]

  [[1 4 1]
   [0 0 3]
   [4 4 3]]]


 [[[1 3 0]
   [4 1 2]
   [3 4 2]]

  [[3 0 0]
   [1 2 1]
   [4 2 4]]

  [[0 0 0]
   [2 1 3]
   [2 4 1]]

  [[0 0 4]
   [1 3 2]
   [4 1 2]]

  [[0 4 3]
   [3 2 4]
   [1 2 1]]

  [[4 3 0]
   [2 4 4]
   [2 1 4]]

  [[3 0 0]
   [4 4 4]
   [1 4 0]]

  [[0 0 3]
   [4 4 3]
   [4 0 3]]]


 [[[4 1 2]
   [3 4 2]
   [0 1 2]]

  [[1 2 1]
   [4 2 4]
   [1 2 2]]

  [[2 1 3]
   [2 4 1]
   [2 2 1]]

  [[1 3 2]
   [4 1 2]
   [2 1 1]]

  [[3 2 4]
   [1 2 1]
   [1 1 1]]

  [[2 4 4]
   [2 1 4]
   [1 1 4]]

  [[4 4 4]
   [1 4 0]
   [1 4 2]]

  [[4 4 3]
   [4 0 3]
   [4 2 0]]]


 [[[3 4 2]
   [0 1 2]
   [0 4 4]]

  [[4 2 4]
   [1 2 2]
   [4 4 3]]

  [[2 4 1]
   [2 2 1]
   [4 3 2]]

  [[4 1 2]
   [2 1 1]
   [3 2 1]]

  [[1 2 1]
   

**11)** Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [19]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


**12)** Дан массив 16x16, посчитать сумму по блокам 4x4

In [21]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


**13)** Найти n наибольших значений в массиве

In [22]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9998 9996 9995]


**14)** Построить прямое произведение массивов (все комбинации с каждым элементом)

In [23]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**15)** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [24]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 2 4]


**16)** Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [25]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 1 3]
 [1 0 3]
 [3 2 2]
 [4 3 4]
 [2 4 3]
 [4 1 4]
 [2 2 3]
 [4 2 0]
 [4 2 2]
 [2 3 2]]
[[2 1 3]
 [1 0 3]
 [3 2 2]
 [4 3 4]
 [2 4 3]
 [4 1 4]
 [2 2 3]
 [4 2 0]
 [4 2 2]
 [2 3 2]]


**17)** Преобразовать вектор чисел в матрицу бинарных представлений

In [26]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [9]:
# обратное представление из бинарной матрицы в вектор
A = np.array([[1,0,1],
              [0,1,0],
              [1,1,0],
              [0,0,1]])

B = np.packbits(A, axis=-1)
print(B)

[[160]
 [ 64]
 [192]
 [ 32]]


**18)** Дан двумерный массив. Найти все различные строки

In [27]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


**19)** Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [29]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[5.68418020e-01, 4.98618112e-01, 3.38276734e-03, 2.69255865e-01,
        7.37709075e-01, 2.02129124e-01, 4.32864680e-02, 6.80564469e-01,
        4.98119900e-01, 7.42379398e-01],
       [1.99123829e-01, 1.74672062e-01, 1.18502504e-03, 9.43236437e-02,
        2.58428569e-01, 7.08083200e-02, 1.51637825e-02, 2.38410110e-01,
        1.74497532e-01, 2.60064641e-01],
       [3.22253529e-01, 2.82681830e-01, 1.91779408e-03, 1.52649370e-01,
        4.18229796e-01, 1.14593171e-01, 2.45404202e-02, 3.85832774e-01,
        2.82399378e-01, 4.20877545e-01],
       [6.48589101e-01, 5.68944441e-01, 3.85988120e-03, 3.07232377e-01,
        8.41757383e-01, 2.30637914e-01, 4.93916983e-02, 7.76552961e-01,
        5.68375960e-01, 8.47086421e-01],
       [4.48108596e-01, 3.93082299e-01, 2.66678232e-03, 2.12266085e-01,
        5.81568082e-01, 1.59347161e-01, 3.41246015e-02, 5.36518509e-01,
        3.92689537e-01, 5.85249901e-01],
       [1.74617584e-01, 1.53175105e-01, 1.03918356e-03, 8.27151972e-02,
   