                                                 Московский Авиационный Институт  
                                          (Национальный Исследовательский Университет)
                                          
Кафедра: 806 «Вычислительная математика и программирование»  
Институт: «Информационные технологии и прикладная математика»  
Дисциплина: «Разработка ПО для высокопроизводительных систем»  

<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                 Лабораторная работа №2.  
                                                          Тема:  
                                                         «numpy»
                                                         
                                                         
                                                                                                       Группа: М8О – 103М-20
                                                                                        Студент: Проскурин Андрей Кириллович
                                                                                Преподаватель: Поповкин Александр Викторович
<br/><br/>
<br/><br/>
<br/><br/>
<br/><br/>

                                                           Москва  
                                                            2020

In [1]:
import numpy as np
import scipy.spatial
from io import StringIO

**1)** Перемножить матрицы 5x3 и 3x2

In [2]:
list = np.dot(np.ones((5,3)), np.ones((3,2)))
print(list)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**2)** Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
list = np.arange(11)
print(list)
list[(3 < list) & (list <= 8)] *= -1
print(list)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


**3)** Создать 5x5 матрицу со значениями в строках от 0 до 4

In [4]:
list = np.zeros((5,5))
list += np.arange(5)
print(list)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**4)** Есть генератор, сделать с его помощью массив

In [9]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**5)** Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [10]:
list = np.linspace(0,1,12)[1:-1]
print(list)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**6)** Отсортировать вектор

In [11]:
list = np.random.random(10)
list.sort()
print(list)

[0.22895305 0.26004683 0.31820191 0.35602958 0.52543528 0.54093129
 0.55886056 0.61121609 0.71690507 0.9334007 ]


**7)** Проверить, одинаковы ли 2 numpy массива

In [12]:
list_1 = np.random.randint(0,2,5)
list_2 = np.random.randint(0,2,5)
similar = np.allclose(list_1,list_2)
print(list_1)
print(list_2)
print(similar)

[1 0 0 0 1]
[1 1 0 0 0]
False


**8)** Сделать массив неизменяемым

In [13]:
list = np.zeros(10, int)
list.flags.writeable = False
print(list)
list[0] = 1
print(list)

[0 0 0 0 0 0 0 0 0 0]


ValueError: assignment destination is read-only

**9)** Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

Функция hypot() вычисляет длинну гипотенузы по указанным значениям катетов. Эквивалентно sqrt(x1**2 + x2**2).  

Функция arctan2() вычисляет arctan(x1/x2) и возвращает значение угла в правильном квадранте (четверти координатной плоскости).

In [14]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.13380097 1.15448088 0.49687159 0.0692655  1.19551852 0.88532485
 0.92692404 0.99773932 0.82808622 0.67466365]
[0.82433612 0.76935505 0.1632067  0.35748866 0.80481582 0.72071766
 0.99299989 0.65462345 0.13900779 0.21204847]


**10)** Заменить максимальный элемент на ноль

In [15]:
list = np.random.random(10)
list[list.argmax()] = 0
print(list)

[0.         0.41684245 0.72934515 0.3321341  0.70762947 0.16022305
 0.52137075 0.36562435 0.30778645 0.26971257]


**11)** Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]  

**Syntax: numpy.meshgrid**  

Функция **meshgrid()** создает список массивов координатных сеток N-мерного координатного пространства для указанных одномерных массивов координатных векторов. Координатное пространство - это пространство N-мерных точек-координат, причем каждой точке в таком пространстве соответствует комбинация одного значения из каждого координатного массива.

```numpy.meshgrid(x1, x2,..., xn, **kwargs)```  

**x1, x2,..., xn** - последовательность. Одномерные массивы, которые определяют координатную сетку.  
**indexing** - ‘xy’, ‘ij’ (необязательный). Определяет декартово ‘xy’ (по умолчанию) или матричное ‘ij’ индексирование выходного массива.  
**sparse** - True или False (необязательный). Если True, то для экономии памяти выводятся сжатые до одной оси массивы координатных сеток. По умолчанию sparse = False.  
**copy** - True или False (необязательный). Если False, то для экономии памяти возвращается представление исходных координатных массивов. По умолчанию copy = True.  

**Возврощает**  
**результат** - ```[X1, X2, X3, ... , Xn]``` - список массивов NumPy  

Для N входных одномерных координатных векторов возвращается список массивов координатных cеток. Если длинна координатных массивов len(x1) = L1; len(x2) = L2; len(xN) = LN, то при indexing = 'ij' размеры массивов координатных сеток будут равны (L1, L2, L3, ... , LN). В случае, если параметр indexing = 'xy', то размеры массивов координатных сеток будут (L2, L1, L3, ... , LN), при этом повторение элементов так же окажется несколько инным.  

В двумерном случае, когда длинна массива x1 равна M, а длинна вектора x2 равна N, то при indexing = 'xy' размеры массивов координатных сеток будут равны (N, M), а при indexing = 'ij' (M, N).  

Допускаются случаи 0-мерного и 1-мерного пространства.

In [16]:
list = np.zeros((10,10), [('x',float),('y',float)])
list['x'], list['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(list)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

**12)** Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))  

Функция subtract() вычисляет поэлементную разность значений массивов x1 и x2.

In [17]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


**13)** Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [18]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


**14)** Напечатать все значения в массиве

In [19]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((7,7))
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**15)** Найти ближайшее к заданному значению число в заданном массиве

In [20]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

94


**16)** Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [21]:
 list = np.zeros(10, [ ('position', [ ('x', int, 1),
                                   ('y', int, 1)]),
                    ('color',    [ ('r', int, 1),
                                   ('g', int, 1),
                                   ('b', int, 1)])])
print(list)

[((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0)) ((0, 0), (0, 0, 0))
 ((0, 0), (0, 0, 0))]


<ipython-input-21-fb5fe96cd293>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  list = np.zeros(10, [ ('position', [ ('x', int, 1),


**17)** Дан массив (100,2) координат, найти расстояние от каждой точки до каждой  

scipy.spatial.distance.cdist - вычисляет расстояние между каждой парой из двух наборов входных данных.

In [23]:
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.35448995 0.51637714 0.09788173 0.41882096 0.3182543
  0.51643355 0.18959843 0.2554288  0.52091297]
 [0.35448995 0.         0.79617607 0.28801844 0.18637658 0.67269697
  0.71505335 0.33528787 0.51373347 0.35346615]
 [0.51637714 0.79617607 0.         0.61353528 0.91747496 0.38109846
  0.20004456 0.69770787 0.28341277 0.72539055]
 [0.09788173 0.28801844 0.61353528 0.         0.32518716 0.39845988
  0.60323552 0.11217798 0.34655525 0.51929004]
 [0.41882096 0.18637658 0.91747496 0.32518716 0.         0.72009775
  0.86546953 0.30640251 0.63607941 0.53748339]
 [0.3182543  0.67269697 0.38109846 0.39845988 0.72009775 0.
  0.50384633 0.42901245 0.31219254 0.78198965]
 [0.51643355 0.71505335 0.20004456 0.60323552 0.86546953 0.50384633
  0.         0.70589878 0.26278763 0.56807338]
 [0.18959843 0.33528787 0.69770787 0.11217798 0.30640251 0.42901245
  0.70589878 0.         0.44493871 0.61510255]
 [0.2554288  0.51373347 0.28341277 0.34655525 0.63607941 0.31219254
  0.26278763 0.444938

**18)** Преобразовать массив из float в int

In [30]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(type(Z[0]))

<class 'numpy.int32'>


**19)** Дан файл:  
1, 2, 3, 4, 5  
6 ,,, 7, 8  
, , 9, 10, 11  
Как прочитать его?

In [34]:
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


**20)** Каков эквивалент функции enumerate для numpy массивов?

Класс ndenumerate() создает объект итератора, который возвращающает пары с индексом элементов в массиве и их значением.  

Класс ndindex() создает объект итератора, который возвращающает индексы элементов в массиве заданной формы.

In [35]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


**21)** Сформировать 2D массив с распределением Гаусса

In [36]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

**22)** Случайно расположить p элементов в 2D массив

In [11]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), [1, 2, 3])
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]]


**23)** Отнять среднее из каждой строки в матрице

In [54]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.10389555 -0.00367374 -0.13600143 -0.19297387  0.33748482 -0.42626406
   0.09757962 -0.13965206  0.49962396 -0.14001878]
 [-0.24053347 -0.30018887  0.29556374  0.02960047 -0.13901343  0.21839154
  -0.24533097 -0.10875182  0.24998961  0.24027319]
 [-0.52480068  0.15059551  0.36989427 -0.17508852  0.03267449  0.23995592
  -0.35109289 -0.08630159  0.1762336   0.16792987]
 [-0.31276211  0.17645598  0.0623192  -0.06449231  0.27681217 -0.19398662
   0.19765041 -0.24000918  0.16805829 -0.07004582]
 [ 0.04901801  0.52487406  0.04975161 -0.00843654  0.40907774  0.06738965
  -0.43385107 -0.25203292 -0.0608265  -0.34496404]]


**24)** Отсортировать матрицу по n-ому столбцу

In [56]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[0 7 5]
 [4 8 4]
 [9 3 1]]
[[9 3 1]
 [0 7 5]
 [4 8 4]]


**25)** Определить, есть ли в 2D массиве нулевые столбцы

.any - Проверяет, есть ли среди указанных элементов хотя бы один, принимающий значение «истина».

In [59]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


**26)** Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)  

Функция bincount() возвращает количество вхождений значений в массиве.

In [64]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 3. 2. 3. 2. 4. 4. 2. 5.]


**27)** Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [68]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


**28)** Дан четырехмерный массив, посчитать сумму по последним двум осям

In [69]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 63 82 73]
 [47 60 62 54]
 [60 49 60 61]]


**29)** Найти диагональные элементы произведения матриц

In [70]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([1.40678085, 2.03095185, 0.72437479, 1.28803216, 0.73157593])